export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';

export const ADD_SERVICE_REQUEST    = 'ADD_SERVICE_REQUEST';
export const ADD_SERVICE_FAILURE    = 'ADD_SERVICE_FAILURE';
export const ADD_SERVICE_SUCCESS    = 'ADD_SERVICE_SUCCESS';

export const REMOVE_SERVICE         = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD   = 'CHANGE_SERVICE_FIELD';

export const FETCH_HITS_SUCCESS = "FETCH_HITS_SUCCESS";
export const FETCH_CATALOG_SUCCESS = "FETCH_CATALOG_SUCCESS";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_ID_SUCCESS = "FETCH_ID_SUCCESS";

export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_OFFSET = "CHANGE_OFFSET";
export const CHANGE_SEARCH_REQUEST = "CHANGE_SEARCH_REQUEST";
export const CHANGE_SEARCH_INPUT = "CHANGE_SEARCH_INPUT";

export const SELECT_COUNT = "SELECT_COUNT";
export const SELECT_SIZE = "SELECT_SIZE";
export const SELECT_CART_ITEM_PROPERTIES_TO_SAVE = "SELECT_CART_ITEM_PROPERTIES_TO_SAVE";
export const CART_ITEM_TO_INITIAL = "CART_ITEM_TO_INITIAL";

export const CHANGE_CART_LIST = "CHANGE_CART_LIST";
export const CHANGE_COST = "CHANGE_COST";

export const GET_LOCALSTORAGE_SUCCESS = "GET_LOCALSTORAGE_SUCCESS";
export const GET_LOCALSTORAGE_FAILURE = "GET_LOCALSTORAGE_FAILURE";
export const SET_LOCALSTORAGE_SUCCESS = "SET_LOCALSTORAGE_SUCCESS";
export const SET_LOCALSTORAGE_FAILURE = "SET_LOCALSTORAGE_FAILURE";
export const CHANGE_ORDER_FIELD = "CHANGE_ORDER_FIELD";

export const FETCH_HITS_REQUEST = "FETCH_HITS_REQUEST";
export const FETCH_HITS_FAILURE = "FETCH_HITS_FAILURE";

export const FETCH_ID_REQUEST = "FETCH_ID_REQUEST";
export const FETCH_ID_FAILURE = "FETCH_ID_FAILURE";
export const FETCH_CATALOG_REQUEST = "FETCH_CATALOG_REQUEST";
export const FETCH_CATALOG_FAILURE = "FETCH_CATALOG_FAILURE";
// export const CHANGE_ORDER_FIELD = "CHANGE_ORDER_FIELD";
// export const FETCH_ID_FAILURE = "FETCH_ID_FAILURE";
export const FETCH_CATEGORIES_REQUEST = "FETCH_CATALOG_REQUEST";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATALOG_FAILURE";